/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guet_pyl_gobang_Chessboard */

#ifndef _Included_guet_pyl_gobang_Chessboard
#define _Included_guet_pyl_gobang_Chessboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    StartGame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_StartGame
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    AddPiece
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_AddPiece
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    NextMove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_NextMove
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    CheckGameOver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_CheckGameOver
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    GetGrid
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_GetGrid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    GetChengWu
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_guet_pyl_gobang_Chessboard_GetChengWu
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    GetLastStep
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_guet_pyl_gobang_Chessboard_GetLastStep
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    GetStepsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_GetStepsCount
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    GetBoardSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guet_pyl_gobang_Chessboard_GetBoardSize
  (JNIEnv *, jobject);

/*
 * Class:     guet_pyl_gobang_Chessboard
 * Method:    ClearChessBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guet_pyl_gobang_Chessboard_ClearChessBoard
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_guet_pyl_gobang_Chessboard_SetBoardSize
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_guet_pyl_gobang_Chessboard_SetDiffcult
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
